import 'package:flutter/material.dart';

/* Rectangle file-20191024-31453-10p3sbb 1
    Autogenerated by FlutLab FTF Generator
  */
class File201910243145310p3sbb1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 122.0,
      height: 82.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/74b275b4f44bf1b47d7faf198bb04ba0a1829853.png",
          color: null,
          fit: BoxFit.cover,
          width: 122.0,
          height: 82.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
