import 'package:flutter/material.dart';

/* Rectangle Screenshot 2021-11-20 at 10.24 1
    Autogenerated by FlutLab FTF Generator
  */
class Screenshot20211120at10241Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 147.0,
      height: 88.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/ab180c3d5b38a7724d423475f47dd01f004b50d3.png",
          color: null,
          fit: BoxFit.cover,
          width: 147.0,
          height: 88.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
