import 'package:flutter/material.dart';
import 'package:keep_water_app/screens/overview/widgets/Vector51Widget.dart';
import 'package:keep_water_app/screens/overview/widgets/Vector17Widget.dart';
import 'package:keep_water_app/screens/overview/widgets/W30Widget.dart';
import 'package:keep_water_app/screens/overview/widgets/UnionWidget.dart';
import 'package:keep_water_app/screens/overview/widgets/Rectangle8Widget2.dart';
import 'package:keep_water_app/screens/overview/widgets/WorldwideblueWidget.dart';
import 'package:keep_water_app/screens/overview/widgets/Ellipse28Widget.dart';
import 'package:keep_water_app/screens/overview/widgets/Vector54Widget.dart';
import 'package:keep_water_app/screens/overview/widgets/W482litersWidget.dart';
import 'package:keep_water_app/screens/overview/widgets/Vector50Widget.dart';
import 'package:keep_water_app/screens/overview/widgets/Rectangle10Widget.dart';
import 'package:keep_water_app/screens/overview/widgets/W5Widget.dart';
import 'package:keep_water_app/screens/overview/widgets/WaterconsumptionWidget.dart';
import 'package:keep_water_app/screens/overview/widgets/Ellipse25Widget.dart';
import 'package:keep_water_app/screens/overview/widgets/FlowrateWidget.dart';
import 'package:keep_water_app/screens/overview/widgets/Vector49Widget.dart';
import 'package:keep_water_app/screens/overview/widgets/Ellipse26Widget.dart';
import 'package:keep_water_app/screens/overview/widgets/Vector53Widget.dart';
import 'package:keep_water_app/screens/overview/widgets/TeethcleaningtimeWidget.dart';
import 'package:keep_water_app/screens/overview/widgets/AverageshowertimeWidget.dart';
import 'package:keep_water_app/screens/overview/widgets/Vector57Widget.dart';
import 'package:keep_water_app/screens/overview/widgets/EnergyconsumptionWidget.dart';
import 'package:keep_water_app/screens/overview/widgets/DishwashesWidget.dart';
import 'package:keep_water_app/screens/overview/widgets/Ellipse30Widget.dart';
import 'package:keep_water_app/screens/overview/widgets/ThisNovemberWidget.dart';
import 'package:keep_water_app/screens/overview/widgets/W1min32secsWidget.dart';
import 'package:keep_water_app/screens/overview/widgets/Rectangle11Widget.dart';
import 'package:keep_water_app/screens/overview/widgets/W110lminWidget.dart';
import 'package:keep_water_app/screens/overview/widgets/Ellipse27Widget.dart';
import 'package:keep_water_app/screens/overview/widgets/Vector55Widget.dart';
import 'package:keep_water_app/screens/overview/widgets/Heat1Widget.dart';
import 'package:keep_water_app/screens/overview/widgets/W8min53secsWidget.dart';
import 'package:keep_water_app/screens/overview/widgets/Vector16Widget.dart';
import 'package:keep_water_app/screens/overview/widgets/Vector56Widget.dart';
import 'package:keep_water_app/screens/overview/widgets/TemperatureWidget.dart';
import 'package:keep_water_app/screens/overview/widgets/Vector52Widget.dart';
import 'package:keep_water_app/screens/overview/widgets/Rectangle3Widget3.dart';
import 'package:keep_water_app/screens/overview/widgets/Rectangle6Widget3.dart';
import 'package:keep_water_app/screens/overview/widgets/Vector48Widget.dart';
import 'package:keep_water_app/screens/overview/widgets/Ellipse29Widget.dart';
import 'package:keep_water_app/screens/overview/widgets/Rectangle7Widget2.dart';
import 'package:keep_water_app/screens/overview/widgets/W126kWhWidget.dart';
import 'package:keep_water_app/screens/overview/widgets/Rectangle9Widget.dart';
import 'package:keep_water_app/screens/overview/widgets/Vector15Widget.dart';

/* Frame habbits-overview
    Autogenerated by FlutLab FTF Generator
  */
class Overview extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      child: Container(
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: -270.0,
                top: -284.07720947265625,
                right: null,
                bottom: null,
                width: 930.4766235351562,
                height: 826.8451538085938,
                child: WorldwideblueWidget(),
              ),
              Positioned(
                left: 25.4765625,
                top: 541.75341796875,
                right: null,
                bottom: null,
                width: 340.0,
                height: 123.0,
                child: Rectangle11Widget(),
              ),
              Positioned(
                left: 38.4765625,
                top: 556.75341796875,
                right: null,
                bottom: null,
                width: 234.0,
                height: 28.0,
                child: EnergyconsumptionWidget(),
              ),
              Positioned(
                left: 25.4765625,
                top: 25.75341796875,
                right: null,
                bottom: null,
                width: 161.0,
                height: 101.0,
                child: Rectangle3Widget3(),
              ),
              Positioned(
                left: 4.4765625,
                top: 74.75341796875,
                right: null,
                bottom: null,
                width: 156.0,
                height: 44.0,
                child: W30Widget(),
              ),
              Positioned(
                left: 25.4765625,
                top: 281.75341796875,
                right: null,
                bottom: null,
                width: 129.0,
                height: 101.0,
                child: Rectangle8Widget2(),
              ),
              Positioned(
                left: 113.13330078125,
                top: 327.75341796875,
                right: null,
                bottom: null,
                width: 17.773332595825195,
                height: 17.773332595825195,
                child: Ellipse25Widget(),
              ),
              Positioned(
                left: 133.11279296875,
                top: 322.75341796875,
                right: null,
                bottom: null,
                width: 12.813333511352539,
                height: 12.813333511352539,
                child: Ellipse26Widget(),
              ),
              Positioned(
                left: 130.26220703125,
                top: 310.75341796875,
                right: null,
                bottom: null,
                width: 8.680000305175781,
                height: 8.680000305175781,
                child: Ellipse27Widget(),
              ),
              Positioned(
                left: 119.85205078125,
                top: 336.9794921875,
                right: null,
                bottom: null,
                width: 6.2074666023254395,
                height: 6.822540283203125,
                child: Vector15Widget(),
              ),
              Positioned(
                left: 138.2490234375,
                top: 330.24609375,
                right: null,
                bottom: null,
                width: 3.5489094257354736,
                height: 3.6397809982299805,
                child: Vector16Widget(),
              ),
              Positioned(
                left: 133.794921875,
                top: 316.53369140625,
                right: null,
                bottom: null,
                width: 1.8880938291549683,
                height: 1.7724733352661133,
                child: Vector17Widget(),
              ),
              Positioned(
                left: 34.4765625,
                top: 328.70068359375,
                right: null,
                bottom: null,
                width: 40.78947448730469,
                height: 46.05263137817383,
                child: W5Widget(),
              ),
              Positioned(
                left: 70.26611328125,
                top: 328.70068359375,
                right: null,
                bottom: null,
                width: 86.21052551269531,
                height: 43.05263137817383,
                child: ThisNovemberWidget(),
              ),
              Positioned(
                left: 172.4765625,
                top: 281.75341796875,
                right: null,
                bottom: null,
                width: 193.0,
                height: 101.0,
                child: Rectangle9Widget(),
              ),
              Positioned(
                left: 326.13330078125,
                top: 327.75341796875,
                right: null,
                bottom: null,
                width: 17.773332595825195,
                height: 17.773332595825195,
                child: Ellipse28Widget(),
              ),
              Positioned(
                left: 313.4765625,
                top: 317.146728515625,
                right: null,
                bottom: null,
                width: 12.813333511352539,
                height: 12.813333511352539,
                child: Ellipse29Widget(),
              ),
              Positioned(
                left: 338.26220703125,
                top: 310.75341796875,
                right: null,
                bottom: null,
                width: 8.680000305175781,
                height: 8.680000305175781,
                child: Ellipse30Widget(),
              ),
              Positioned(
                left: 332.85205078125,
                top: 336.9794921875,
                right: null,
                bottom: null,
                width: 6.2074666023254395,
                height: 6.822540283203125,
                child: Vector55Widget(),
              ),
              Positioned(
                left: 321.1005859375,
                top: 322.08544921875,
                right: null,
                bottom: null,
                width: 3.5489094257354736,
                height: 3.6397809982299805,
                child: Vector56Widget(),
              ),
              Positioned(
                left: 341.318359375,
                top: 424.7802734375,
                right: null,
                bottom: null,
                width: 1.8880938291549683,
                height: 1.7724733352661133,
                child: Vector57Widget(),
              ),
              Positioned(
                left: 185.4765625,
                top: 330.75341796875,
                right: null,
                bottom: null,
                width: 213.16966247558594,
                height: 38.999813079833984,
                child: W1min32secsWidget(),
              ),
              Positioned(
                left: 25.4765625,
                top: 144.75341796875,
                right: null,
                bottom: null,
                width: 340.0,
                height: 119.0,
                child: Rectangle7Widget2(),
              ),
              Positioned(
                left: 34.4765625,
                top: 196.75341796875,
                right: null,
                bottom: null,
                width: 313.0,
                height: 56.0,
                child: W8min53secsWidget(),
              ),
              Positioned(
                left: 25.4765625,
                top: 400.75341796875,
                right: null,
                bottom: null,
                width: 340.0,
                height: 123.0,
                child: Rectangle10Widget(),
              ),
              Positioned(
                left: 35.4765625,
                top: 455.75341796875,
                right: null,
                bottom: null,
                width: 505.0,
                height: 56.0,
                child: W482litersWidget(),
              ),
              Positioned(
                left: 36.4765625,
                top: 596.75341796875,
                right: null,
                bottom: null,
                width: 505.0,
                height: 56.0,
                child: W126kWhWidget(),
              ),
              Positioned(
                left: 204.4765625,
                top: 25.75341796875,
                right: null,
                bottom: null,
                width: 161.0,
                height: 101.0,
                child: Rectangle6Widget3(),
              ),
              Positioned(
                left: 206.4765625,
                top: 74.75341796875,
                right: null,
                bottom: null,
                width: 154.0,
                height: 41.0,
                child: W110lminWidget(),
              ),
              Positioned(
                left: 38.4765625,
                top: 155.75341796875,
                right: null,
                bottom: null,
                width: 243.0,
                height: 28.0,
                child: AverageshowertimeWidget(),
              ),
              Positioned(
                left: 38.4765625,
                top: 292.75341796875,
                right: null,
                bottom: null,
                width: 138.0,
                height: 31.0,
                child: DishwashesWidget(),
              ),
              Positioned(
                left: 217.4765625,
                top: 36.75341796875,
                right: null,
                bottom: null,
                width: 144.0,
                height: 28.0,
                child: FlowrateWidget(),
              ),
              Positioned(
                left: 185.4765625,
                top: 292.75341796875,
                right: null,
                bottom: null,
                width: 182.0,
                height: 25.0,
                child: TeethcleaningtimeWidget(),
              ),
              Positioned(
                left: 38.4765625,
                top: 415.75341796875,
                right: null,
                bottom: null,
                width: 234.0,
                height: 28.0,
                child: WaterconsumptionWidget(),
              ),
              Positioned(
                left: 38.4765625,
                top: 36.75341796875,
                right: null,
                bottom: null,
                width: 128.0,
                height: 31.0,
                child: TemperatureWidget(),
              ),
              Positioned(
                left: 140.0,
                top: 184.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 37.0,
                child: Heat1Widget(),
              ),
              Positioned(
                left: 131.4765625,
                top: 67.640869140625,
                right: null,
                bottom: null,
                width: 41.99990463256836,
                height: 48.11247253417969,
                child: Vector48Widget(),
              ),
              Positioned(
                left: 144.68359375,
                top: 83.2451171875,
                right: null,
                bottom: null,
                width: 16.254213333129883,
                height: 25.35657501220703,
                child: Vector49Widget(),
              ),
              Positioned(
                left: 302.4765625,
                top: 64.75341796875,
                right: null,
                bottom: null,
                width: 42.5,
                height: 12.0,
                child: Vector50Widget(),
              ),
              Positioned(
                left: 302.9765625,
                top: 54.75341796875,
                right: null,
                bottom: null,
                width: 42.5,
                height: 12.0,
                child: Vector51Widget(),
              ),
              Positioned(
                left: 302.9765625,
                top: 44.75341796875,
                right: null,
                bottom: null,
                width: 42.5,
                height: 12.0,
                child: Vector52Widget(),
              ),
              Positioned(
                left: 257.4765625,
                top: 163.75341796875,
                right: null,
                bottom: null,
                width: 66.0,
                height: 38.0,
                child: UnionWidget(),
              ),
              Positioned(
                left: 309.00616455078125,
                top: 205.75341796875,
                right: null,
                bottom: null,
                width: 14.276280403137207,
                height: 15.229334831237793,
                child: Vector53Widget(),
              ),
              Positioned(
                left: 317.41796875,
                top: 214.578857421875,
                right: null,
                bottom: null,
                width: 1.0,
                height: 3.0,
                child: Vector54Widget(),
              )
            ]),
      ),
    ));
  }
}
