import 'package:flutter/material.dart';

/* Rectangle Rectangle 2177
    Autogenerated by FlutLab FTF Generator
  */
class Rectangle2177Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 216.0,
      height: 176.00123596191406,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(231.67459106445312),
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(127, 0, 111, 247),
            offset: Offset(0.0, 8.802206993103027),
            blurRadius: 71.8547592163086,
          )
        ],
        gradient: LinearGradient(
          begin: Alignment(0.0, -1.0),
          end: Alignment(0.0, 0.9999999999999998),
          stops: [0.0, 0.484375],
          colors: [
            Color.fromARGB(255, 0, 85, 188),
            Color.fromARGB(255, 0, 111, 247)
          ],
        ),
      ),
    );
  }
}
