import 'package:flutter/material.dart';
import 'package:keep_water_app/screens/home/widgets/Widget6.dart';

/* Frame ringcentralsans-arrow-right
    Autogenerated by FlutLab FTF Generator
  */
class RingcentralsansarrowrightWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 14.0,
      height: 12.44073486328125,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 4.547473508864641e-13,
              top: 1.2441059350967407,
              right: null,
              bottom: null,
              width: 14.0,
              height: 9.94316291809082,
              child: Widget6(),
            )
          ]),
    );
  }
}
