import 'package:flutter/material.dart';
import 'package:keep_water_app/screens/home/widgets/Widget7.dart';

/* Frame ringcentralsans-arrow-right
    Autogenerated by FlutLab FTF Generator
  */
class RingcentralsansarrowrightWidget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 14.0,
      height: 12.440765380859375,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 4.547473508864641e-13,
              top: 1.244109034538269,
              right: null,
              bottom: null,
              width: 14.0,
              height: 9.943187713623047,
              child: Widget7(),
            )
          ]),
    );
  }
}
