import 'package:flutter/material.dart';
import 'package:keep_water_app/helpers/svg/svg.dart';

/* BooleanOperation Union
    Autogenerated by FlutLab FTF Generator
  */
class UnionWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 13.705426216125488,
      height: 34.000125885009766,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M4.74425 20.6252L4.74425 2.37209C4.74425 1.06202 5.80627 0 7.11635 0C8.42642 0 9.48844 1.06202 9.48844 2.37209L9.48844 20.8199C11.9648 21.8527 13.7054 24.2968 13.7054 27.1474C13.7054 30.9321 10.6374 34.0001 6.85271 34.0001C3.06806 34.0001 0 30.9321 0 27.1474C0 24.0984 1.99126 21.5145 4.74425 20.6252Z')
          ..color = Color.fromARGB(255, 44, 124, 246),
      ]),
    );
  }
}
