name: "keep_water_app"
description: A app to help you stop wasting water.
publish_to: "none"
version: "1.0.0+1"
dependencies:
  flutter:
    sdk: "flutter"
  cupertino_icons: "^0.1.3"
  path_drawing: "^0.4.1"
  flutter_lints: ^1.0.4
  flutter_svg: ^0.19.3
  flutter_vector_icons: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: "flutter"
environment:
  sdk: ">=2.7.0 <3.0.0"
flutter:
  assets:
    - "assets/"
    - "assets/images/"
    - "assets/images/navBar/"
  fonts:
    -
      family: "Poppins"
      fonts:
        -
          asset: "fonts/Poppins-600.ttf"
          style: "normal"
          weight: 600
        -
          asset: "fonts/Poppins-regular.ttf"
          style: "normal"
          weight: 400
        -
          asset: "fonts/Poppins-500.ttf"
          style: "normal"
          weight: 500
        -
          asset: "fonts/Poppins-200.ttf"
          style: "normal"
          weight: 200
        -
          asset: "fonts/Poppins-300.ttf"
          style: "normal"
          weight: 300
  uses-material-design: true
