import 'package:flutter/material.dart';
import 'package:keep_water_app/screens/profile/widgets/Widget5.dart';

/* Frame ringcentralsans-arrow-right
    Autogenerated by FlutLab FTF Generator
  */
class RingcentralsansarrowrightWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 14.0,
      height: 12.440673828125,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 4.547473508864641e-13,
              top: 1.2440954446792603,
              right: null,
              bottom: null,
              width: 14.0,
              height: 9.943111419677734,
              child: Widget5(),
            )
          ]),
    );
  }
}
