import 'package:flutter/material.dart';
import 'package:keep_water_app/screens/friends/widgets/MaskGroupWidget11.dart';
import 'package:keep_water_app/screens/friends/widgets/MyhomeWidget.dart';
import 'package:keep_water_app/screens/friends/widgets/TikkanenshomeWidget.dart';
import 'package:keep_water_app/screens/friends/widgets/Rectangle3Widget4.dart';
import 'package:keep_water_app/screens/friends/widgets/W458Widget.dart';
import 'package:keep_water_app/screens/friends/widgets/MaskGroupWidget9.dart';
import 'package:keep_water_app/screens/friends/widgets/Rectangle9Widget1.dart';
import 'package:keep_water_app/screens/friends/widgets/MaskGroupWidget7.dart';
import 'package:keep_water_app/screens/friends/widgets/MaskGroupWidget6.dart';
import 'package:keep_water_app/screens/friends/widgets/MaskGroupWidget8.dart';
import 'package:keep_water_app/screens/friends/widgets/W531Widget.dart';
import 'package:keep_water_app/screens/friends/widgets/W469Widget.dart';
import 'package:keep_water_app/screens/friends/widgets/Rectangle8Widget3.dart';
import 'package:keep_water_app/screens/friends/widgets/KarvonenshomeWidget.dart';
import 'package:keep_water_app/screens/friends/widgets/Rectangle7Widget3.dart';
import 'package:keep_water_app/screens/friends/widgets/LatvalashomeWidget.dart';
import 'package:keep_water_app/screens/friends/widgets/Rectangle6Widget4.dart';
import 'package:keep_water_app/screens/friends/widgets/W500Widget.dart';
import 'package:keep_water_app/screens/friends/widgets/OjalashomeWidget.dart';
import 'package:keep_water_app/screens/friends/widgets/WirtanenshomeWidget.dart';
import 'package:keep_water_app/screens/friends/widgets/Rectangle10Widget1.dart';
import 'package:keep_water_app/screens/friends/widgets/MaskGroupWidget10.dart';
import 'package:keep_water_app/screens/friends/widgets/W436Widget.dart';
import 'package:keep_water_app/screens/friends/widgets/W530Widget.dart';
import 'package:keep_water_app/screens/friends/widgets/ChallengeendsthisSunday10at2359Widget.dart';
import 'package:keep_water_app/screens/friends/widgets/Vector9Widget.dart';

/* Frame friends-1
    Autogenerated by FlutLab FTF Generator
  */
class Friends extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      child: Container(
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(40.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 25.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 70.0,
                child: Rectangle3Widget4(),
              ),
              Positioned(
                left: 25.0,
                top: 254.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 70.0,
                child: Rectangle7Widget3(),
              ),
              Positioned(
                left: 25.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 70.0,
                child: Rectangle8Widget3(),
              ),
              Positioned(
                left: 25.0,
                top: 444.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 70.0,
                child: Rectangle9Widget1(),
              ),
              Positioned(
                left: 25.0,
                top: 539.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 70.0,
                child: Rectangle10Widget1(),
              ),
              Positioned(
                left: 25.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 70.0,
                child: Rectangle6Widget4(),
              ),
              Positioned(
                left: 101.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 28.0,
                child: KarvonenshomeWidget(),
              ),
              Positioned(
                left: 101.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 28.0,
                child: LatvalashomeWidget(),
              ),
              Positioned(
                left: 101.0,
                top: 374.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 28.0,
                child: WirtanenshomeWidget(),
              ),
              Positioned(
                left: 101.0,
                top: 469.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 28.0,
                child: OjalashomeWidget(),
              ),
              Positioned(
                left: 101.0,
                top: 564.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 28.0,
                child: TikkanenshomeWidget(),
              ),
              Positioned(
                left: 101.0,
                top: 184.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 28.0,
                child: MyhomeWidget(),
              ),
              Positioned(
                left: 295.0,
                top: 86.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 31.0,
                child: W436Widget(),
              ),
              Positioned(
                left: 295.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 31.0,
                child: W469Widget(),
              ),
              Positioned(
                left: 295.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 31.0,
                child: W500Widget(),
              ),
              Positioned(
                left: 295.0,
                top: 466.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 31.0,
                child: W530Widget(),
              ),
              Positioned(
                left: 295.0,
                top: 561.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 31.0,
                child: W531Widget(),
              ),
              Positioned(
                left: 295.0,
                top: 181.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 31.0,
                child: W458Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 28.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 28.0,
                child: ChallengeendsthisSunday10at2359Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 74.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: MaskGroupWidget6(),
              ),
              Positioned(
                left: 35.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: MaskGroupWidget7(),
              ),
              Positioned(
                left: 35.0,
                top: 359.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: MaskGroupWidget8(),
              ),
              Positioned(
                left: 35.0,
                top: 454.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: MaskGroupWidget9(),
              ),
              Positioned(
                left: 35.0,
                top: 549.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: MaskGroupWidget10(),
              ),
              Positioned(
                left: 35.0,
                top: 169.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: MaskGroupWidget11(),
              ),
              Positioned(
                left: 193.0,
                top: 640.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 12.0,
                child: Vector9Widget(),
              )
            ]),
      ),
    ));
  }
}
